export const GET_TODOS_REQUEST = 'GET_TODOS_REQUEST';
export const GET_TODOS_SUCCESS = 'GET_TODOS_SUCCESS';
export const GET_TODOS_FAILURE = 'GET_TODOS_FAILURE';
export const UPDATE_TODO_COMPLETE = 'UPDATE_TODO_COMPLETE';
export const UPDATE_TODO_COMPLETE_SUCCESS = 'UPDATE_TODO_COMPLETE_SUCCESS';